### PR TITLE
Preselect language if no cookie set

### LINKED ISSUE #185: No language preselected
**Describe the bug**
There is no language preselected.

**To Reproduce**
1. Go to the specmate login page
2. No translated text, but only default texts are displayed until the user selects a language manually.

**Expected behavior**
The language is preselected based on the browser language.

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by sebeder**
[Trello Card](https://trello.com/c/EDQeAOLc/744-language-cookie-wird-nicht-richtig-gesetzt)

closes #185

### CODE REVIEW

File: web/src/app/modules/common/modules/i18n/components/language-chooser.component.ts [hunk 1]
```diff
@@ -78,7 +83,11 @@ export class LanguageChooser implements OnInit {
     }
 
     private retrieveFromCookie(): string {
-        return this.cookiesService.getCookie(LanguageChooser.LANGUAGE_KEY);
+        const language = this.cookiesService.getCookie(LanguageChooser.LANGUAGE_KEY);
+        if (language !== undefined) {
+            return language.replace(/(^")/, '').replace(/"$/, '');
```
Comment (junkerm) [inline web/src/app/modules/common/modules/i18n/components/language-chooser.component.ts:89]: please add comment ("Remove starting and trailing quote, because....")

**Review by junkerm — APPROVED** [review]
only minor comment, otherwise: works and looks good --> then merge
