### PR TITLE
Remove error if empty linked node is copied

### LINKED ISSUE #304: Kopieren von leerem Linked node führt zu fehler
**Describe the bug**
Wenn man einen leeren verlinkten knoten kopiert, dann gibt es einen Fehler

**To Reproduce**
1. Verlinkten Knoten erstellen
2. den Ursprungsknoten löschen
3. -> der verlinkte Knoten ist jetzt leer
4. Verlinkten Knoten kopieren
 -> Fehler in der Console

### PR DESCRIPTION
**Pull request by wehrlean**
Closes #304

### CODE REVIEW

File: web/src/app/modules/views/main/editors/modules/tool-pallette/tools/ceg/ceg-linked-node-tool.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export class CEGLinkedNodeTool extends CreateNodeToolBase<CEGLinkedNode> impleme
     public async perform(compoundId = Id.uuid): Promise<CEGLinkedNode> {
         let node = await super.perform();
         let linkedNode: CEGNode = undefined;
-        if (this.value !== undefined && Type.is(this.value, CEGLinkedNode)) {
+        if (this.value !== undefined && Type.is(this.value, CEGLinkedNode) && (this.value as CEGLinkedNode).linkTo) {
```
Comment (sebeder) [inline web/src/app/modules/views/main/editors/modules/tool-pallette/tools/ceg/ceg-linked-node-tool.ts]: Please specify, which value linkTo should have (undefined, null or []) - Otherwise this might lead to issues.

**Review by sebeder — CHANGES_REQUESTED** [review]

**Review by sebeder — APPROVED** [review]
