### PR TITLE
Fix undo cegeditor

### LINKED ISSUE #192: Rückgängig Funktion funktioniert nicht richtig im CEG Editor
**Describe the bug**
Wenn man ein Modell aufbaut und dann mehrmals auf Rückgängig klickt, wird das Modell auf nicht nachvollziehbare Weise verändert (Änderungen werden z.B. Rückgängig gemacht und dann wiederholt). Außerdem geht der Wiederholen Knopf nicht.

**To Reproduce**
1) Erstelle neues CEG Modell und speichere
2) navigiere irgendwohin und wieder zurück zum modell
3) füge knoten hinzu
4) Rückgängig --> Knoten wird nicht entfernt sondern irgend etwas anderes wird gemacht

### LINKED ISSUE #205: Rückgangigfunktion funktioniert im CEG Editor beim gleichen Modell nicht
**Describe the bug**
Wenn man zu einem CEG-Modell etwas hinzufügt, speichert, zur Anforderung wechselt und dann zum CEG-Modell zurückkehrt, zeigt der Editor ein nicht richtiges Verhalten bei der Rückgängigfunktion.

**To Reproduce**
1. CEG-Modell erstellen
2. Knoten anlegen und umbennenen
3. Speichern
4. Zur Anforderung des CEGs wechseln
5. Zurück zum CEG wechseln
6. Neuen Knoten hinzufügen
7. Rückgängig klicken

-> Fehler: Das Umbenennen des ersten Knotens wird ebenfalls rückgängig gemacht

### PR DESCRIPTION
**Pull request by wehrlean**
Fixes #192 
Fixes #205

### CODE REVIEW

File: web/src/app/modules/views/main/editors/modules/graphical-editor/components/graphical-editor.component.ts [hunk 1]
```diff
@@ -79,7 +82,6 @@ export class GraphicalEditor {
         private undoService: UndoService,
         private modal: ConfirmationModal,
         private graphicalEditorService: GraphicalEditorService) {
-
         this.navigator.navigationStart.subscribe(() => {
             this.isInGraphTransition = true;
         });
```
Comment (wehrlean) [inline web/src/app/modules/views/main/editors/modules/graphical-editor/components/graphical-editor.component.ts:87]: I am not that sure about the lifecycle in Angular, but should we unsubscribe the navigation events as well?

Comment (sebeder) [reply web/src/app/modules/views/main/editors/modules/graphical-editor/components/graphical-editor.component.ts:87]: I resolved this. See the last commit.

**Review by sebeder — APPROVED** [review]
