### PR TITLE
Fix UI tests

### LINKED ISSUE #350: UI Tests
Make UI Test work again

### PR DESCRIPTION
**Pull request by wehrlean**
Closes #350

### CODE REVIEW

File: ui-tests/src/test/java/com/specmate/uitests/TestBase.java [hunk 1]
```diff
@@ -11,120 +14,126 @@
...
+		this.deviceOrientation = deviceOrientation;
+	}
+
+	/** Browser configurations */
+	@Parameters
+	public static LinkedList<String[]> browsersStrings() {
+		LinkedList<String[]> browsers = new LinkedList<String[]>();
+
+		browsers.add(new String[] { "Windows 10", "88.0", "Chrome", null, null });
+		// browsers.add(new String[]{"Windows 10", "18.17763", "MicrosoftEdge", null,
```
Comment (sebeder) [inline ui-tests/src/test/java/com/specmate/uitests/TestBase.java:74]: Please remove the commented code.

**Review by sebeder — CHANGES_REQUESTED** [review]
This is fine, except the one comment I have. And we need the unit tests to run in that branch so that the ui tests are executed. @junkerm , could you please have a look at that?

File: ui-tests/src/test/java/com/specmate/uitests/TestBase.java (hunk 1 above)
Comment (wehrlean) [reply ui-tests/src/test/java/com/specmate/uitests/TestBase.java:74]: I leave it there on purpose, because if we want to run on multiple browsers we can easily do it. But I can also remove it, since we are only using Chrome for years, because on the other the tests fails

**Comment by sebeder** [comment]
Hi @junkerm , then it is only the red unit test that needs to be fixed, could you have a look at that?

**Comment by sebeder** [comment]
Hi @junkerm , just a ping that we do not forget the issue. With the fix, we'd have a UI without warnings and a clean build.

**Comment by junkerm** [comment]
@sebeder I modified the test case - it should run now
